language: node_js
node_js:
    - "5"
script:
    - |
        cat <<EOF > src/secrets.js
        export const clientId = 'placeholder';
        export const clientSecret = 'placeholder';
        EOF
    - npm test
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    - npm run lint
